
project_id = "wgmvohihwaffavfstmfr"

[functions.fetchtokensupply]
verify_jwt = false

[functions.tokenSupplyAPI]
verify_jwt = false

[functions.chainBreakdownAPI]
verify_jwt = false

[functions.combinedTokenAPI]
verify_jwt = false
