
project_id = "wgmvohihwaffavfstmfr"

[functions.fetchtokensupply]
verify_jwt = false

[functions.tokensupplyapi]
verify_jwt = false

[functions.chainbreakdownapi]
verify_jwt = false

[functions.combinedtokenapi]
verify_jwt = false

[functions.tokenholderapi]
verify_jwt = false

[functions.historical-price]
verify_jwt = false

[functions.combinedTokenAPI]
verify_jwt = false
