// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdpqfgsmgugxdogqelvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkcHFmZ3NtZ3VneGRvZ3FlbHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDU5NzEsImV4cCI6MjA1ODgyMTk3MX0.vDWuAtRuQ_Ik0N2KrwFqKebKCL7U3TT_76dDRjRC9Mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);